language: c

dist: stretch

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - pgdg
    - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'
      key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
    - postgresql-11
	- postgis
	- liblwgeom-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

