language: c

dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y postgresql-11 postgis liblwgeom-dev libpq-dev libpqtypes-dev postgresql-server-dev-11

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test

